2024-08-30 16:49:55,398 - slowapi - ERROR - Failed to configure throttling for __mp_main__.trigger_error (couldn't parse rate limit string '0.5/second') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-08-30 16:49:55,453 - slowapi - ERROR - Failed to configure throttling for server_fastapi.trigger_error (couldn't parse rate limit string '0.5/second') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-02 09:30:44,655 - peluqueria_mael - ERROR - Error Inesperado: 'dict' object has no attribute 'email' - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/public/main.py:188
2024-09-02 09:32:20,358 - peluqueria_mael - ERROR - Error Inesperado: 'dict' object has no attribute 'email' - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/public/main.py:188
2024-09-02 09:35:47,906 - peluqueria_mael - ERROR - Error Inesperado: 'dict' object has no attribute 'email' - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/public/main.py:188
2024-09-02 09:39:32,651 - peluqueria_mael - ERROR - Error Inesperado: 'dict' object has no attribute 'email' - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/public/main.py:194
2024-09-02 09:40:55,638 - peluqueria_mael - ERROR - Error Inesperado: 'dict' object has no attribute 'email' - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/public/main.py:195
2024-09-02 09:41:08,333 - peluqueria_mael - ERROR - Error Inesperado: 'dict' object has no attribute 'email' - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/public/main.py:195
2024-09-02 09:42:59,755 - peluqueria_mael - ERROR - Error Inesperado: 'dict' object has no attribute 'email' - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/public/main.py:195
2024-09-02 09:44:03,923 - peluqueria_mael - ERROR - Error Inesperado: Error de validación: 1 validation error for EncryptText
text
  Value error, El texto contiene caracteres especiales no permitidos. [type=value_error, input_value='fuck_yo', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/public/main.py:195
2024-09-02 09:50:54,980 - peluqueria_mael - ERROR - Error Inesperado: Error de validación: 1 validation error for EncryptText
text
  Value error, El texto contiene caracteres especiales no permitidos. [type=value_error, input_value='fuck_yo', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/public/main.py:195
2024-09-02 09:51:52,892 - peluqueria_mael - ERROR - Error Inesperado: Error de validación: 1 validation error for EncryptText
text
  Value error, El texto contiene caracteres especiales no permitidos. [type=value_error, input_value='fuck_yo', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/public/main.py:195
2024-09-02 09:52:02,889 - peluqueria_mael - ERROR - Error Inesperado: Error de validación: 1 validation error for EncryptText
text
  Value error, El texto contiene caracteres especiales no permitidos. [type=value_error, input_value='fuck_yo', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/public/main.py:195
2024-09-02 09:53:33,684 - peluqueria_mael - ERROR - Error Inesperado: 1 validation error for Info
email
  value is not a valid email address: An email address must have an @-sign. [type=value_error, input_value=b'7d4dc79a6d37b78347e9e59...bc40024dd46495eceab6333', input_type=bytes] - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/public/main.py:195
2024-09-02 09:54:05,041 - peluqueria_mael - ERROR - Error Inesperado: 1 validation error for Info
email
  value is not a valid email address: An email address must have an @-sign. [type=value_error, input_value=b'b595c271102d499cc2ceb42...a93548093617b0b183d6280', input_type=bytes] - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/public/main.py:195
2024-09-02 10:19:33,635 - peluqueria_mael - ERROR - Error Inesperado: Error de validación: 1 validation error for EncryptText
text
  Value error, El texto contiene caracteres especiales no permitidos. [type=value_error, input_value='LzzmC(cb(AOG#dEG97On-HjJ...U!g)6+WRIDv4ccYjX#@OCYs', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/public/main.py:195
2024-09-02 10:38:56,914 - peluqueria_mael - ERROR - Error a la hora de insertar el usuario VALIDATION_ERROR: 1 validation error for Add
data.info
  Input should be a valid dictionary or instance of Info [type=model_type, input_value=InfoEncrypted(email='b595...cc7eace795b98f29e2ac9d'), input_type=InfoEncrypted]
    For further information visit https://errors.pydantic.dev/2.8/v/model_type - /peluqueriamael/Backend/microservices/app/API/v1/crud/mongodb/users/add.py:97
2024-09-02 19:18:27,203 - slowapi - ERROR - Failed to configure throttling for routes.client.public.main.Loggin_User (couldn't parse rate limit string '1/2m') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-02 19:19:36,251 - slowapi - ERROR - Failed to configure throttling for routes.client.public.main.Loggin_User (couldn't parse rate limit string '1/2s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-02 19:20:28,253 - slowapi - ERROR - Failed to configure throttling for routes.client.public.main.Loggin_User (couldn't parse rate limit string '3/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-02 20:58:01,801 - peluqueria_mael - ERROR - {'info': 'No se encontró la cita en la estructura.', 'status': 'no', 'type': 'APPOINTMENT_NOT_FOUND'} - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/restricted/booking/main.py:253
2024-09-02 20:58:18,930 - peluqueria_mael - ERROR - {'info': 'No se encontró la cita en la estructura.', 'status': 'no', 'type': 'APPOINTMENT_NOT_FOUND'} - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/restricted/booking/main.py:253
2024-09-03 09:01:57,332 - peluqueria_mael - ERROR - Error Inesperado: [Errno 111] Connection refused - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/public/main.py:208
2024-09-03 09:01:57,468 - peluqueria_mael - ERROR - Error Inesperado: [Errno 111] Connection refused - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/public/main.py:208
2024-09-03 09:34:04,009 - peluqueria_mael - ERROR - {'info': 'No se encontró la cita en la estructura.', 'status': 'no', 'type': 'APPOINTMENT_NOT_FOUND'} - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/restricted/booking/main.py:253
2024-09-03 09:34:52,648 - peluqueria_mael - ERROR - {'info': 'No se encontró la cita en la estructura.', 'status': 'no', 'type': 'APPOINTMENT_NOT_FOUND'} - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/restricted/booking/main.py:253
2024-09-03 09:35:14,399 - peluqueria_mael - ERROR - {'info': 'No se encontró la cita en la estructura.', 'status': 'no', 'type': 'APPOINTMENT_NOT_FOUND'} - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/restricted/booking/main.py:253
2024-09-03 10:48:11,895 - peluqueria_mael - ERROR - ERROR APPOINTMENT: 1 validation error for structure
user
  String should have at most 32 characters [type=string_too_long, input_value='8641b94034bb08f2b4d41f5b...d930d7d73e229ca6a1da8a8', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/string_too_long - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/restricted/booking/main.py:519
2024-09-03 10:48:40,716 - peluqueria_mael - ERROR - ERROR APPOINTMENT: 1 validation error for structure
user
  String should have at most 32 characters [type=string_too_long, input_value='8641b94034bb08f2b4d41f5b...d930d7d73e229ca6a1da8a8', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/string_too_long - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/restricted/booking/main.py:519
2024-09-03 10:49:27,940 - peluqueria_mael - ERROR - ERROR APPOINTMENT: 1 validation error for structure
user
  String should have at most 32 characters [type=string_too_long, input_value='8641b94034bb08f2b4d41f5b...d930d7d73e229ca6a1da8a8', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/string_too_long - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/restricted/booking/main.py:519
2024-09-03 12:08:09,124 - peluqueria_mael - ERROR - {'info': 'No se encontró la cita en la estructura.', 'status': 'no', 'type': 'APPOINTMENT_NOT_FOUND'} - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/restricted/booking/main.py:249
2024-09-03 12:08:26,481 - peluqueria_mael - ERROR - {'info': 'No se encontró la cita en la estructura.', 'status': 'no', 'type': 'APPOINTMENT_NOT_FOUND'} - /peluqueriamael/Backend/microservices/app/API/v1/routes/client/restricted/booking/main.py:249
2024-09-04 01:47:25,015 - slowapi - ERROR - Failed to configure throttling for routes.client.public.main.Loggin_User (couldn't parse rate limit string '3/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:49:38,041 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Remove_Appointment_Options (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:49:42,589 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Remove_Appointment_Options (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:49:47,696 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Remove_Appointment_Options (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:49:52,397 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Remove_Appointment_Options (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:50:17,236 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Remove_Appointment_Options (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:50:19,483 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Remove_Appointment_Options (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:51:14,618 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Remove_Appointment_Options (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:51:20,107 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Remove_Appointment_Options (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:51:35,586 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Remove_Appointment_Options (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:51:45,570 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Remove_Appointment_Options (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:52:02,418 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Remove_Appointment_Options (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:55:58,363 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Remove_Appointment (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:55:58,366 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Add_Appointment_Options (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:56:32,714 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Remove_Appointment (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:56:32,717 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Add_Appointment (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:56:32,721 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.data.main.Data_Appointments_Options (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:56:45,127 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Remove_Appointment (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:56:45,130 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Add_Appointment (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:56:45,135 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.data.main.Data_Appointments (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:56:45,136 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.data.main.Data_Services_Options (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:01,908 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Remove_Appointment (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:01,913 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Add_Appointment (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:01,919 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.data.main.Data_Appointments (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:01,919 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.data.main.Data_Services (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:01,921 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.data.main.Data_Booking_Day_Sheet (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:01,926 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.user.config.main.Config_Reset_Password_Options (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:27,666 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Remove_Appointment (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:27,670 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Add_Appointment (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:27,672 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.data.main.Data_Appointments (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:27,673 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.data.main.Data_Services (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:27,675 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.data.main.Data_Booking_Day_Sheet (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:27,680 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.user.config.main.Config_Reset_Password (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:27,683 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.user.main.User_Delete_Options (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:35,367 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Remove_Appointment (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:35,371 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Add_Appointment (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:35,374 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.data.main.Data_Appointments (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:35,375 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.data.main.Data_Services (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:35,377 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.data.main.Data_Booking_Day_Sheet (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:35,381 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.user.config.main.Config_Reset_Password (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:35,384 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.user.main.User_Delete (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:35,421 - slowapi - ERROR - Failed to configure throttling for routes.client.public.main.Loggin_User (couldn't parse rate limit string '3/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:35,428 - slowapi - ERROR - Failed to configure throttling for routes.client.main.Status_Options (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:47,995 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Remove_Appointment (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:47,999 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Add_Appointment (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:48,002 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.data.main.Data_Appointments (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:48,003 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.data.main.Data_Services (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:48,005 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.data.main.Data_Booking_Day_Sheet (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:48,008 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.user.config.main.Config_Reset_Password (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:48,012 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.user.main.User_Delete (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:48,053 - slowapi - ERROR - Failed to configure throttling for routes.client.public.main.Loggin_User (couldn't parse rate limit string '3/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:57:48,060 - slowapi - ERROR - Failed to configure throttling for routes.client.main.Status (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:59:31,181 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Remove_Appointment (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:59:31,184 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.booking.main.Add_Appointment (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:59:31,187 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.data.main.Data_Appointments (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:59:31,188 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.data.main.Data_Services (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:59:31,190 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.data.main.Data_Booking_Day_Sheet (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:59:31,193 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.user.config.main.Config_Reset_Password (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:59:31,196 - slowapi - ERROR - Failed to configure throttling for routes.client.restricted.user.main.User_Delete (couldn't parse rate limit string '5/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
2024-09-04 01:59:31,235 - slowapi - ERROR - Failed to configure throttling for routes.client.public.main.Loggin_User (couldn't parse rate limit string '3/10s') - /usr/local/lib/python3.12/site-packages/slowapi/extension.py:695
